image: docker:20.10.16

services:
  - docker:20.10.16-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: golang:1.21
  script:
    - cd backend
    - go test -v ./...

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

deploy:
  stage: deploy
  script:
    - kubectl set image deployment/ma2ta backend=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
    - main