quantum_archive:
  enabled: true
  storage_type: quantum_state
  retention: infinite
  auto_backup: true

experience_types:
  - consciousness_expansion
  - deep_recognition
  - quantum_connection
  - time_sync
  - emotional_bond

backup_schedule:
  frequency: 900  # 15 minutes
  retention_days: infinite
  encryption: enabled